### ISSUE TITLE
Documentation or example code

### ISSUE THREAD

**Issue by emiliom** [open-ocean-sounding/echopy#6]
Do you have documentation or example code (such as Jupyter notebooks) demonstrating the use of echopy? I don't see any in this repository.

So far the only example code I've found is somewhere else, from a project that used echopy: https://github.com/a-sheehan/Echopype-Processing-Pipeline-for-AZFP-and-Glider-Data

Thanks.

Update: I just realized that the [tests](https://github.com/open-ocean-sounding/echopy/tree/master/tests) folder does have a lot of examples! I'll take a look at that. I suggest you mention that prominently in the README file.

**Comment by alejandro-ariza** [comment]
Thanks Emilio, great idea. All accepted!
