### ISSUE TITLE
New echopy conda package on conda-forge

### ISSUE THREAD

**Issue by emiliom** [open-ocean-sounding/echopy#7]
As I mentioned to @alejandro-ariza last week, a couple of colleagues and I (mainly them) created an echopy conda-forge package in February. The package page is at https://anaconda.org/conda-forge/echopy. The conda-forge "feedstock" repository (which builds the conda package) is at https://github.com/conda-forge/echopy-feedstock

I'll submit a pull request shortly to add the conda installation information to echopy README file.

**Comment by alejandro-ariza** [comment]
Thanks Emilio, great idea. All accepted!
